[Variables]
lineGraphAa=1
lineGraphBgType=1
tempUnits=F

scale=1.2
tScale=1.2

cornerRoundness=3

showBgBorder=1
rowSpacing=1
barTextOffset=1
barHeight=1
graphHeight=42
graphWidth=#contentWidth#

; Sidebars
setupSb=1
sbSetupMode=Placement

sb1Enabled=0
sb1MaskType=acrylic
sb1MaskColor=0,0,0
sb1MaskAlpha=150
sb1Columns=1
sb1Alignment=left
sb1Monitor=1

sb2Enabled=0
sb2MaskType=acrylic
sb2MaskColor=0,0,0
sb2MaskAlpha=150
sb2Columns=1
sb2Alignment=right
sb2Monitor=2

colorSbControlCorner=0,0,3

colorBorder=31,251,255
colorBg=0,0,0
colorBgBorder=#colorBorder#
colorSubBg=87,87,87

colorGraphBg=#colorSubBg#
colorGraphBorder=#colorBorder#
colorGraphGrid=#colorGraphBorder#

colorMain=255,255,255
colorDim=4,94,209
colorAccent=255,255,255
colorDisabled=100,100,100

colorBarBg=#colorBorder#

colorError=200,53,53

colorInputBg=#colorSubBg#
colorInputBorder=#colorBorder#
colorInputText=#colorDim#
