[Variables]
; - INCLUDED -
; coordinates
latitude=39.540467
longitude=-119.748723
; units: one of "e" (imperial), "m" (metric) or "h" (hybrid - celsius with miles, U.K.)
units=e
; language
language=en-US
; update rate
updateRate=600

; - OURS -

showHumidity=1
showUv=1
showUvChart=1
showAtmPressure=1
showVisibility=0
showDewpoint=0
showWindInfo=1
showSunMoonInfo=0
showMoonAngle=1

timeFormat=WinShort
customTimeFormat=...
